services:
  web:
    container_name: shop-flow-web
    environment:
      APP_VERSION: "0.1.1"
      MOV_PERSISTENCY_TYPE: "LiteDB"
    image: algiro/shop-flow-net:latest
    volumes:
      - type: bind
        source: ${SHOP_FLOW_MOVS_VOLUME}
        target: /data/shopFlowMovs
    ports: []
    networks:
      - microservices
  app-gateway:
    container_name: nginx
    build:
      context: ./app-gateway
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
    networks:
      - microservices

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_URL}
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_UPSTREAM: "http://shop-flow-web:8080"
      OAUTH2_PROXY_HTTP_ADDRESS: "http://0.0.0.0:4180"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".localhost:3000"
    secrets:
      - oauth2_proxy_client_id
      - oauth2_proxy_client_secret
      - oauth2_proxy_cookie_secret
      - oauth2_proxy_redirect_url
    command:
      - --http-address=0.0.0.0:4180
      - --upstream=http://shop-flow-web:8080
      # - --skip-provider-button=true
    networks:
      - microservices

networks:
  microservices:


volumes:
  shopFlowMovs:
  certs:


secrets:
  oauth2_proxy_client_id:
    environment: OAUTH2_PROXY_CLIENT_ID
  oauth2_proxy_client_secret:
    environment: OAUTH2_PROXY_CLIENT_SECRET
  oauth2_proxy_cookie_secret:
    environment: OAUTH2_PROXY_COOKIE_SECRET
  oauth2_proxy_redirect_url:
    environment: OAUTH2_PROXY_REDIRECT_URL
