name: Build and publish Docker image to DockerHub
on:
  [workflow_dispatch]
  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . -t algiro/shop-flow-net:latest
      - name: Push image to DockerHub
        run: |
          docker login -u algiro -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push algiro/shop-flow-net:latest